name: mysql_examp
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.9.3

# Add regular dependencies here.
dependencies:
  mysql1: ^0.20.0
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
